const router = require('express').Router();
const db = require('../../database/db');
const md5 = require('md5');
const jwt = require('jsonwebtoken');
const checkAuth = require('../../middleware/auth_check');
const { generateKeyPair } = require('crypto');
// so db connection is reqd in route file

router.post('/create',(req, res)=>{
    const {fullName,email} = req.body;
    const password = req.body.password;
    const encrytPassword = md5(password);
    // console.log(fullName, email,password)
    // console.log(password,encrytPassword)

   db.query(
       "insert into users (full_name, email, password, status) values (?,?,?,?)",
       [fullName,email,encrytPassword,'1'],
       (error, result)=>{
          if(error){
              return res.status(500).json({
                  error:error
              })
          }
          return res.status(200).json({
              message: "registered successfully"
          })
       }
   )

})

router.post('/login',(req, res)=>{
    const email = req.body.email;
    const password = req.body.password;
    const encrytPassword = md5(password);
    db.query(
        "select user_id, password from users where email = ?",
        [email],
        (error,result)=>{
            if(error){
                return res.status(500).json({
                    error:error
                })
            }
            else if (!result[0]){
                return res.status(404).json({
                    status: 0, 
                    message: "email id dosen't exit, register first"
                })
            }
            //results returned from db are in the form of arrays
            else if (result[0].password === encrytPassword){

                // each time a user log's in-> a new jwt token is generated by the backend and is sent in the res body, which is further saved  by client in 
                // session and used to access prfile
                // when  the user logos out-> the JWT token stored as secret key in db is emptied out 
                // n so now if the user wudnt be able to access profile..once's logged otu..unless they login back
                const jwtToken = jwt.sign(
                    {
                        id: Buffer.from(result[0].user_id.toString()).toString('base64')
                    },
                    process.env.JWT_KEY,
                    {
                        expiresIn: "1hr"
                    }
                );

                // save the token in DB
                db.query(
                    "update users set secret_key = ? where user_id = ?",
                    [jwtToken, result[0].user_id],
                    (error, result) => {
                        if(error){
                            return res.status(500).json({
                                error:error
                            })
                        }
                        // return the token
                        return res.status(200).json({
                            jwtToken: jwtToken,
                            message:"password matched"
                        })
                    }
                )
            }
            else {
                return res.status(404).json({
                    message:"password Incorrect"
                })
            }
        }

    )
})

router.get('/logout', checkAuth, (req,res)=>{
    // now we will check if the token verified by middleware belongs to our user in question?
    //encoded user id -> is coming from the jwt token, it is part of teh jwt token
    const encodedUserId = res.userData.data.id;
    const userId = Buffer.from(encodedUserId, "base64").toString("ascii");
    //the actual token sent by user, coming from the front end,
    const userToken = res.userData.token; //

    db.query(
        "select secret_key from users where user_id = ?",
        [userId],
        (error, result) => {
            if(error){
                return res.status(500).json({
                    error: error
                })
            }
            else if(result[0].secret_key === userToken){
                // removing the token from database
                db.query(
                    "update users set secret_key = ? where user_id = ?",
                    ['', userId],
                    (error, result) =>{
                        if(error){
                            return res.status(500).json({
                                error: error
                            })
                        }
                        return res.status(200).json({
                            message: "Logout done"
                        })
                    }
                )
            }
            else {
                return res.status(404).json({
                    message: "Token don't match"
                })
            }
        }
    )
})



// const generateKey  = async() => {
//     //generate key
//     generateKeyPair('ec', {
//         namedCurve: 'secp256k1',
//         publicKeyEncoding: {
//             type: 'spki',
//             format: 'der'
//         }
//     },
//     (err, publicKey) => {
//         if(err){
//             console.log("Key genrate error");
//             return 0;
//         } else {
//             console.log("Key : ", publicKey.toString('hex'));
//             return publicKey.toString('hex');
//         }
//     })
//  }



module.exports = router;